SELECT nombre FROM producto;
SELECT nombre, precio FROM producto;
SELECT * FROM producto;
SELECT nombre, precio AS 'Preu Euros', ROUND(precio / 1.2, 2) AS 'Preu Dolars' FROM producto;
SELECT nombre AS 'nom de producte', precio AS 'euros', ROUND(precio / 1.2, 2) AS 'dolars' FROM producto;
SELECT UPPER(nombre), precio FROM producto;
SELECT LOWER(nombre), precio FROM producto;
SELECT nombre , LEFT(UPPER(nombre),2) FROM fabricante;
SELECT nombre, ROUND(precio) FROM producto;
SELECT nombre, TRUNCATE(precio, 0) FROM producto;
SELECT fabricante.codigo FROM fabricante JOIN producto ON codigo_fabricante = fabricante.codigo;
SELECT fabricante.codigo FROM fabricante JOIN producto ON codigo_fabricante = fabricante.codigo GROUP BY codigo_fabricante;
SELECT nombre  FROM tienda.fabricante ORDER BY nombre;
SELECT nombre FROM tienda.fabricante ORDER BY nombre desc;
SELECT nombre, precio FROM producto ORDER BY nombre, precio desc;
SELECT *  FROM tienda.fabricante LIMIT 5;
SELECT *  FROM tienda.fabricante LIMIT 3,2;
SELECT nombre, precio  FROM tienda.producto ORDER BY precio LIMIT 1;
SELECT nombre, precio  FROM tienda.producto ORDER BY precio desc LIMIT 1;
SELECT producto.nombre FROM producto JOIN  fabricante WHERE  codigo_fabricante = 2;
SELECT producto.nombre, precio, fabricante.nombre FROM producto JOIN  fabricante;
SELECT producto.nombre, precio, fabricante.nombre FROM producto JOIN  fabricante ORDER BY producto.nombre;
SELECT producto.codigo, producto.nombre, fabricante.codigo,  fabricante.nombre FROM producto JOIN  fabricante;
SELECT producto.nombre AS 'Producte més barat', MIN(producto.precio) AS 'Preu' ,   fabricante.nombre AS 'Fabricant'  FROM producto JOIN  fabricante;
SELECT producto.nombre AS 'Producte més car', Max(producto.precio) AS 'Preu' ,   fabricante.nombre AS 'Fabricant'  FROM producto JOIN  fabricante;
SELECT producto.nombre AS 'Producte', fabricante.nombre AS 'Fabricant'  FROM producto JOIN  fabricante WHERE  codigo_fabricante = 2;
SELECT producto.nombre AS 'Producte', fabricante.nombre AS 'Fabricant' ,producto.precio FROM producto JOIN  fabricante WHERE  codigo_fabricante = 6 AND producto.precio >= 200;
SELECT producto.nombre AS 'Producte', fabricante.nombre AS 'Fabricant' ,producto.precio FROM producto JOIN  fabricante WHERE  codigo_fabricante = 1 OR codigo_fabricante = 3 OR codigo_fabricante = 5;
SELECT producto.nombre AS 'Producte', fabricante.nombre AS 'Fabricant' ,producto.precio FROM producto JOIN  fabricante WHERE codigo_fabricante IN (1, 3, 5);
SELECT producto.nombre AS 'Producte', producto.precio FROM producto JOIN  fabricante WHERE  RIGHT(fabricante.nombre,1) = 'e';
SELECT producto.nombre AS 'Producte', producto.precio, fabricante.nombre AS 'Fabricant' FROM producto JOIN  fabricante WHERE LOCATE('W', fabricante.nombre) > 0;
SELECT producto.nombre AS 'Producte', producto.precio, fabricante.nombre AS 'Fabricant' FROM producto JOIN  fabricante WHERE producto.precio >= 180  ORDER BY producto.precio, producto.nombre;
SELECT fabricante.codigo, fabricante.nombre FROM producto JOIN  fabricante ON  fabricante.codigo = producto.codigo; 
SELECT  fabricante.nombre, producto.nombre FROM producto RIGHT JOIN  fabricante ON  fabricante.codigo = producto.codigo ;
SELECT  fabricante.nombre FROM fabricante LEFT JOIN  producto ON  fabricante.codigo = producto.codigo  WHERE producto.codigo IS NULL;
SELECT  producto.nombre, fabricante.nombre FROM producto JOIN  fabricante WHERE fabricante.codigo = 2;
SELECT  producto.nombre, producto.precio, fabricante.nombre FROM producto JOIN  fabricante WHERE (fabricante.codigo = 2);
SELECT  producto.nombre, Max(producto.precio), fabricante.nombre FROM producto JOIN  fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE (fabricante.nombre = 'Lenovo');
SELECT  producto.nombre, Min(producto.precio), fabricante.nombre FROM producto JOIN  fabricante ON producto.codigo_fabricante = fabricante.codigo WHERE (fabricante.nombre = 'Hewlett-Packard');
